C:
  image: etews/gcc-expect-valgrind
  script:
    - make check MEMCHECK=TRUE

Python:
  image: python:3.7-stretch
  script:
    - pip install --upgrade -v .
    - pip install -r requirements-dev.txt
    - coverage run -m pytest -sv
